import {v} from "../estilos/variables";
import {
  AiOutlineHome,
  AiOutlineApartment,
  AiOutlineSetting,
} from "react-icons/ai";
import {MdOutlineAnalytics} from "react-icons/md";
import {RiDashboard3Line} from "react-icons/ri";
import {TbPig} from "react-icons/tb";

export const DesplegableUser = [
  {
    text: "Mi perfil",
    icono: v.iconoUser,
    tipo: "miperfil",
  },
  {
    text: "Configuracion",
    icono: v.iconoSettings,
    tipo: "configuracion",
  },
  {
    text: "Cerrar sesión",
    icono: v.iconoCerrarSesion,
    tipo: "cerrarsesion",
  },
];
//data SIDEBAR
export const LinksArray = [
  {
    label: "Partidos",
    icon: "/svg/balon.svg",
    to: "/futbol/partidos",
  },
  {
    label: "Ligas",
    icon: "/svg/cup.svg",
    to: "/futbol/ligas",
  },
  {
    label: "Buscar",
    icon: "/svg/lupa.svg",
    to: "/futbol/buscar",
  },
  {
    label: "Perfil",
    icon: "/svg/user.svg",
    to: "/futbol/perfil",
  }
];
export const SecondarylinksArray = [
  {
    label: "Configuración",
    icon: <AiOutlineSetting />,
    to: "/configurar",
  },
  {
    label: "Acerca de",
    icon: <TbPig />,
    to: "/acercade",
  },
];
//temas
export const TemasData = [
  {
    icono: "🌞",
    descripcion: "light",
  },
  {
    icono: "🌚",
    descripcion: "dark",
  },
];
// data de juegos
export const JuegosData = [
  {
    id: 444453,
    jornada: 20,
    local: "Napoli",
    emblem_local: "https://crests.football-data.org/113.svg",
    visitante: "Salernitana",
    emblem_visitante: "https://crests.football-data.org/455.png",
    fecha_utc: "2024-01-13 09:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 1,
    arbitro: "Livio Marinelli",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 444447,
    jornada: 20,
    local: "Genoa",
    emblem_local: "https://crests.football-data.org/107.svg",
    visitante: "Torino",
    emblem_visitante: "https://crests.football-data.org/586.svg",
    fecha_utc: "2024-01-13 09:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 0,
    arbitro: "Antonio Giua",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 444448,
    jornada: 20,
    local: "Verona",
    emblem_local: "https://crests.football-data.org/450.png",
    visitante: "Empoli",
    emblem_visitante: "https://crests.football-data.org/445.png",
    fecha_utc: "2024-01-13 12:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "12:00 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 1,
    arbitro: "Daniele Doveri",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 444452,
    jornada: 20,
    local: "Monza",
    emblem_local: "https://crests.football-data.org/5911.png",
    visitante: "Inter",
    emblem_visitante: "https://crests.football-data.org/108.png",
    fecha_utc: "2024-01-13 14:45:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "02:45 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 5,
    arbitro: "Antonio Rapuano",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 444451,
    jornada: 20,
    local: "Milan",
    emblem_local: "https://crests.football-data.org/98.svg",
    visitante: "Roma",
    emblem_visitante: "https://crests.football-data.org/100.svg",
    fecha_utc: "2024-01-13 19:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:00 PM",
    estado: "SCHEDULED",
    idestado: 3,
    goles_local: null,
    goles_visitante: null,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 444450,
    jornada: 20,
    local: "Lazio",
    emblem_local: "https://crests.football-data.org/110.svg",
    visitante: "Lecce",
    emblem_visitante: "https://crests.football-data.org/5890.png",
    fecha_utc: "2024-01-13 19:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:00 PM",
    estado: "SCHEDULED",
    idestado: 3,
    goles_local: null,
    goles_visitante: null,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 444449,
    jornada: 20,
    local: "Juventus",
    emblem_local: "https://crests.football-data.org/109.svg",
    visitante: "Sassuolo",
    emblem_visitante: "https://crests.football-data.org/471.svg",
    fecha_utc: "2024-01-13 19:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:00 PM",
    estado: "SCHEDULED",
    idestado: 3,
    goles_local: null,
    goles_visitante: null,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 444446,
    jornada: 20,
    local: "Fiorentina",
    emblem_local: "https://crests.football-data.org/99.svg",
    visitante: "Udinese",
    emblem_visitante: "https://crests.football-data.org/115.png",
    fecha_utc: "2024-01-13 19:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:00 PM",
    estado: "SCHEDULED",
    idestado: 3,
    goles_local: null,
    goles_visitante: null,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 444445,
    jornada: 20,
    local: "Cagliari",
    emblem_local: "https://crests.football-data.org/104.svg",
    visitante: "Bologna",
    emblem_visitante: "https://crests.football-data.org/103.svg",
    fecha_utc: "2024-01-13 19:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:00 PM",
    estado: "SCHEDULED",
    idestado: 3,
    goles_local: null,
    goles_visitante: null,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 444444,
    jornada: 20,
    local: "Atalanta",
    emblem_local: "https://crests.football-data.org/102.svg",
    visitante: "Frosinone",
    emblem_visitante: "https://crests.football-data.org/470.png",
    fecha_utc: "2024-01-13 19:00:00",
    competicion: "Serie A",
    emblem_competicion: "https://crests.football-data.org/SA.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:00 PM",
    estado: "SCHEDULED",
    idestado: 3,
    goles_local: null,
    goles_visitante: null,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 445547,
    jornada: 17,
    local: "Casa Pia",
    emblem_local: "https://crests.football-data.org/6618.png",
    visitante: "Famalic\u00e3o",
    emblem_visitante: "https://crests.football-data.org/5531.png",
    fecha_utc: "2024-01-13 10:30:00",
    competicion: "Primeira Liga",
    emblem_competicion: "https://crests.football-data.org/PPL.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 2,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 445550,
    jornada: 17,
    local: "Chaves",
    emblem_local:
      "https://upload.wikimedia.org/wikipedia/en/0/05/G_D_Chaves.png",
    visitante: "Sporting CP",
    emblem_visitante: "https://crests.football-data.org/498.png",
    fecha_utc: "2024-01-13 13:00:00",
    competicion: "Primeira Liga",
    emblem_competicion: "https://crests.football-data.org/PPL.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "01:00 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 3,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 445551,
    jornada: 17,
    local: "Estoril Praia",
    emblem_local: "https://crests.football-data.org/582.png",
    visitante: "Moreirense",
    emblem_visitante: "https://crests.football-data.org/583.png",
    fecha_utc: "2024-01-13 15:30:00",
    competicion: "Primeira Liga",
    emblem_competicion: "https://crests.football-data.org/PPL.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "03:30 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 3,
    arbitro: null,
    tipo_arbitro: null,
  },
  {
    id: 436148,
    jornada: 21,
    local: "Chelsea",
    emblem_local: "https://crests.football-data.org/61.png",
    visitante: "Fulham",
    emblem_visitante: "https://crests.football-data.org/63.svg",
    fecha_utc: "2024-01-13 07:30:00",
    competicion: "Premier League",
    emblem_competicion: "https://crests.football-data.org/PL.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 0,
    arbitro: "Anthony Taylor",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436151,
    jornada: 21,
    local: "Newcastle",
    emblem_local: "https://crests.football-data.org/67.png",
    visitante: "Man City",
    emblem_visitante: "https://crests.football-data.org/65.png",
    fecha_utc: "2024-01-13 12:30:00",
    competicion: "Premier League",
    emblem_competicion: "https://crests.football-data.org/PL.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "12:30 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 3,
    arbitro: "Chris Kavanagh",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 442861,
    jornada: 18,
    local: "Monaco",
    emblem_local: "https://crests.football-data.org/548.png",
    visitante: "Stade de Reims",
    emblem_visitante: "https://crests.football-data.org/547.png",
    fecha_utc: "2024-01-13 11:00:00",
    competicion: "Ligue 1",
    emblem_competicion: "https://crests.football-data.org/FL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "11:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 3,
    arbitro: "Fran\u00e7ois Letexier",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 442868,
    jornada: 18,
    local: "Stade Rennais",
    emblem_local: "https://crests.football-data.org/529.png",
    visitante: "Nice",
    emblem_visitante: "https://crests.football-data.org/522.png",
    fecha_utc: "2024-01-13 15:00:00",
    competicion: "Ligue 1",
    emblem_competicion: "https://crests.football-data.org/FL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "03:00 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 0,
    arbitro: "Bastien Dechepy",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 438673,
    jornada: 20,
    local: "Las Palmas",
    emblem_local: "https://crests.football-data.org/275.png",
    visitante: "Villarreal",
    emblem_visitante: "https://crests.football-data.org/94.png",
    fecha_utc: "2024-01-13 08:00:00",
    competicion: "laLiga",
    emblem_competicion: "https://i.postimg.cc/K8q9cTTK/image.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "08:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 3,
    goles_visitante: 0,
    arbitro: "Javier Iglesias Villanueva",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 438671,
    jornada: 20,
    local: "Mallorca",
    emblem_local: "https://crests.football-data.org/89.png",
    visitante: "Celta",
    emblem_visitante: "https://crests.football-data.org/558.svg",
    fecha_utc: "2024-01-13 10:15:00",
    competicion: "laLiga",
    emblem_competicion: "https://i.postimg.cc/K8q9cTTK/image.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:15 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 1,
    arbitro: "V\u00edctor Garc\u00eda Verdura",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 438664,
    jornada: 20,
    local: "Athletic",
    emblem_local: "https://crests.football-data.org/77.png",
    visitante: "Real Sociedad",
    emblem_visitante: "https://crests.football-data.org/92.svg",
    fecha_utc: "2024-01-13 12:30:00",
    competicion: "laLiga",
    emblem_competicion: "https://i.postimg.cc/K8q9cTTK/image.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "12:30 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 1,
    arbitro: "Jos\u00e9 Munuera Montero",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 438666,
    jornada: 20,
    local: "Real Betis",
    emblem_local: "https://crests.football-data.org/90.png",
    visitante: "Granada",
    emblem_visitante: "https://crests.football-data.org/83.svg",
    fecha_utc: "2024-01-13 15:00:00",
    competicion: "laLiga",
    emblem_competicion: "https://i.postimg.cc/K8q9cTTK/image.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "03:00 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 0,
    arbitro: "Guillermo Cuadra Fern\u00e1ndez",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441627,
    jornada: 17,
    local: "Sittard",
    emblem_local: "https://crests.football-data.org/1920.png",
    visitante: "Sparta",
    emblem_visitante: "https://crests.football-data.org/6806.png",
    fecha_utc: "2024-01-13 10:30:00",
    competicion: "Eredivisie",
    emblem_competicion: "https://crests.football-data.org/ED.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 2,
    arbitro: "Erwin Blank",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441628,
    jornada: 17,
    local: "Twente",
    emblem_local: "https://crests.football-data.org/666.png",
    visitante: "AZ",
    emblem_visitante: "https://crests.football-data.org/682.png",
    fecha_utc: "2024-01-13 12:45:00",
    competicion: "Eredivisie",
    emblem_competicion: "https://crests.football-data.org/ED.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "12:45 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 1,
    arbitro: "Serdar G\u00f6z\u00fcb\u00fcy\u00fck",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441629,
    jornada: 17,
    local: "Zwolle",
    emblem_local: "https://crests.football-data.org/684.png",
    visitante: "Heerenveen",
    emblem_visitante: "https://crests.football-data.org/673.png",
    fecha_utc: "2024-01-13 14:00:00",
    competicion: "Eredivisie",
    emblem_competicion: "https://crests.football-data.org/ED.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "02:00 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 2,
    arbitro: "Danny Makkelie",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441630,
    jornada: 17,
    local: "PSV",
    emblem_local: "https://crests.football-data.org/674.png",
    visitante: "Excelsior",
    emblem_visitante: "https://crests.football-data.org/670.png",
    fecha_utc: "2024-01-13 15:00:00",
    competicion: "Eredivisie",
    emblem_competicion: "https://crests.football-data.org/ED.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "03:00 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 3,
    goles_visitante: 1,
    arbitro: "Marc Nagtegaal",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436989,
    jornada: 27,
    local: "Coventry City",
    emblem_local: "https://crests.football-data.org/1076.png",
    visitante: "Leicester City",
    emblem_visitante: "https://crests.football-data.org/338.png",
    fecha_utc: "2024-01-13 07:30:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "07:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 3,
    goles_visitante: 1,
    arbitro: "Darren England",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436993,
    jornada: 27,
    local: "Huddersfield",
    emblem_local: "https://crests.football-data.org/394.png",
    visitante: "Plymouth Arg",
    emblem_visitante: "https://crests.football-data.org/1138.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 1,
    arbitro: "Tom Nield",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436998,
    jornada: 27,
    local: "West Brom",
    emblem_local: "https://crests.football-data.org/74.png",
    visitante: "Blackburn",
    emblem_visitante: "https://crests.football-data.org/59.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 4,
    goles_visitante: 1,
    arbitro: "Stephen Martin",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436987,
    jornada: 27,
    local: "Birmingham",
    emblem_local: "https://crests.football-data.org/332.png",
    visitante: "Swansea",
    emblem_visitante: "https://crests.football-data.org/72.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 2,
    arbitro: "Matt Donohue",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436990,
    jornada: 27,
    local: "Millwall",
    emblem_local: "https://crests.football-data.org/384.png",
    visitante: "Middlesbrough",
    emblem_visitante: "https://crests.football-data.org/343.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 3,
    arbitro: "Andy Davies",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436991,
    jornada: 27,
    local: "Southampton",
    emblem_local: "https://crests.football-data.org/340.png",
    visitante: "Sheffield Wed",
    emblem_visitante: "https://crests.football-data.org/345.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 4,
    goles_visitante: 0,
    arbitro: "Lewis Smith",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436996,
    jornada: 27,
    local: "Preston NE",
    emblem_local: "https://crests.football-data.org/1081.png",
    visitante: "Bristol City",
    emblem_visitante: "https://crests.football-data.org/387.svg",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 0,
    arbitro: "Sam Barrott",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436997,
    jornada: 27,
    local: "Rotherham Utd",
    emblem_local: "https://crests.football-data.org/385.png",
    visitante: "Stoke",
    emblem_visitante: "https://crests.football-data.org/70.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 1,
    arbitro: "Keith Stroud",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436988,
    jornada: 27,
    local: "Cardiff",
    emblem_local: "https://crests.football-data.org/715.png",
    visitante: "Leeds United",
    emblem_visitante: "https://crests.football-data.org/341.png",
    fecha_utc: "2024-01-13 10:00:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "10:00 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 3,
    arbitro: "Oliver Langford",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 436995,
    jornada: 27,
    local: "Ipswich Town",
    emblem_local: "https://crests.football-data.org/349.png",
    visitante: "Sunderland",
    emblem_visitante: "https://crests.football-data.org/71.png",
    fecha_utc: "2024-01-13 12:30:00",
    competicion: "Championship",
    emblem_competicion: "https://crests.football-data.org/ELC.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "12:30 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 2,
    goles_visitante: 1,
    arbitro: "Samuel Allison",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441938,
    jornada: 17,
    local: "1. FC K\u00f6ln",
    emblem_local: "https://crests.football-data.org/1.png",
    visitante: "Heidenheim",
    emblem_visitante: "https://crests.football-data.org/44.svg",
    fecha_utc: "2024-01-13 09:30:00",
    competicion: "Bundesliga",
    emblem_competicion: "https://crests.football-data.org/BL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 1,
    arbitro: "Felix Zwayer",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441935,
    jornada: 17,
    local: "Freiburg",
    emblem_local: "https://crests.football-data.org/17.svg",
    visitante: "Union Berlin",
    emblem_visitante: "https://crests.football-data.org/28.svg",
    fecha_utc: "2024-01-13 09:30:00",
    competicion: "Bundesliga",
    emblem_competicion: "https://crests.football-data.org/BL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 0,
    arbitro: "Christian Dingert",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441940,
    jornada: 17,
    local: "Augsburg",
    emblem_local: "https://crests.football-data.org/16.png",
    visitante: "Leverkusen",
    emblem_visitante: "https://crests.football-data.org/3.png",
    fecha_utc: "2024-01-13 09:30:00",
    competicion: "Bundesliga",
    emblem_competicion: "https://crests.football-data.org/BL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 1,
    arbitro: "Sven Jablonski",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441936,
    jornada: 17,
    local: "Mainz",
    emblem_local: "https://crests.football-data.org/15.png",
    visitante: "Wolfsburg",
    emblem_visitante: "https://crests.football-data.org/11.svg",
    fecha_utc: "2024-01-13 09:30:00",
    competicion: "Bundesliga",
    emblem_competicion: "https://crests.football-data.org/BL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 1,
    goles_visitante: 1,
    arbitro: "Patrick Ittrich",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441934,
    jornada: 17,
    local: "RB Leipzig",
    emblem_local: "https://crests.football-data.org/721.png",
    visitante: "Frankfurt",
    emblem_visitante: "https://crests.football-data.org/19.svg",
    fecha_utc: "2024-01-13 09:30:00",
    competicion: "Bundesliga",
    emblem_competicion: "https://crests.football-data.org/BL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "09:30 AM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 1,
    arbitro: "Frank Willenborg",
    tipo_arbitro: "REFEREE",
  },
  {
    id: 441941,
    jornada: 17,
    local: "Darmstadt",
    emblem_local: "https://crests.football-data.org/55.png",
    visitante: "Dortmund",
    emblem_visitante: "https://crests.football-data.org/4.png",
    fecha_utc: "2024-01-13 12:30:00",
    competicion: "Bundesliga",
    emblem_competicion: "https://crests.football-data.org/BL1.png",
    fecha_formateada: "13 Jan",
    hora_formateada: "12:30 PM",
    estado: "FINISHED",
    idestado: 1,
    goles_local: 0,
    goles_visitante: 3,
    arbitro: "Deniz Aytekin",
    tipo_arbitro: "REFEREE",
  },
];
